In [75]:
import pandas as pd

In [76]:
df = pd.read_excel('Ritiaka GPN.xlsx', sheet_name = 'Sheet1')

In [77]:
df.head(20)

     GPN month
0   GPN1   Jan
1   GPN1   Feb
2   GPN1   May
3   GPN1   Jun
4   GPN1   Jul
5   GPN1   Aug
6   GPN1   Sep
7   GPN1   Oct
8   GPN2   Feb
9   GPN2   Apr
10  GPN2   Jun
11  GPN2   Jul
12  GPN2   Aug
13  GPN2   Sep
14  GPN2   Oct
15  GPN2   Nov
16  GPN3   Jan
17  GPN3   Feb
18  GPN3   Mar
19  GPN3   Apr

In [78]:
def convert_month(month):
    if month == "Jan":
        return 1
    elif month == "Feb":
        return 2
    elif month == "Mar":
        return 3
    elif month == "Apr":
        return 4
    elif month == "May":
        return 5
    elif month == "Jun":
        return 6
    elif month == "Jul":
        return 7
    elif month == "Aug":
        return 8
    elif month == "Sep":
        return 9
    elif month == "Oct":
        return 10
    elif month == "Nov":
        return 11
    elif month == "Dec":
        return 12
    else:
        return month

#df = pd.DataFrame({"month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]})
df["month"] = df["month"].apply(convert_month)

print(df)

     GPN  month
0   GPN1      1
1   GPN1      2
2   GPN1      5
3   GPN1      6
4   GPN1      7
5   GPN1      8
6   GPN1      9
7   GPN1     10
8   GPN2      2
9   GPN2      4
10  GPN2      6
11  GPN2      7
12  GPN2      8
13  GPN2      9
14  GPN2     10
15  GPN2     11
16  GPN3      1
17  GPN3      2
18  GPN3      3
19  GPN3      4
20  GPN3      5
21  GPN3      6
22  GPN3      7
23  GPN3      8
24  GPN3      9
25  GPN3     10
26  GPN3     11
27  GPN3     12

In [79]:
len(df1)

29

In [80]:
def add_missing_months(df):
    for gpn, group in df.groupby("GPN"):
        if len(group) != 12:
            temp_min = group['month'].min()
            temp_max = group['month'].max()
            for month in range( temp_min, temp_max+1):
            #for month in range(1, 13):
                if month not in group["month"].tolist():
                    df = df.append({"GPN": gpn, "month": month}, ignore_index=True)
    return df

#df1 = pd.DataFrame({"gpn": ["A", "B", "C"], "month": [1, 2, 3], "hour": [0, 1, 2]})
df = add_missing_months(df)
df = df.sort_values(by=['GPN','month'])

print(df)

     GPN  month
0   GPN1      1
1   GPN1      2
28  GPN1      3
29  GPN1      4
2   GPN1      5
3   GPN1      6
4   GPN1      7
5   GPN1      8
6   GPN1      9
7   GPN1     10
8   GPN2      2
30  GPN2      3
9   GPN2      4
31  GPN2      5
10  GPN2      6
11  GPN2      7
12  GPN2      8
13  GPN2      9
14  GPN2     10
15  GPN2     11
16  GPN3      1
17  GPN3      2
18  GPN3      3
19  GPN3      4
20  GPN3      5
21  GPN3      6
22  GPN3      7
23  GPN3      8
24  GPN3      9
25  GPN3     10
26  GPN3     11
27  GPN3     12

C:\Users\Nebula\AppData\Local\Temp\ipykernel_6452\2706032479.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"GPN": gpn, "month": month}, ignore_index=True)
C:\Users\Nebula\AppData\Local\Temp\ipykernel_6452\2706032479.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"GPN": gpn, "month": month}, ignore_index=True)
C:\Users\Nebula\AppData\Local\Temp\ipykernel_6452\2706032479.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"GPN": gpn, "month": month}, ignore_index=True)
C:\Users\Nebula\AppData\Local\Temp\ipykernel_6452\2706032479.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"GPN": gpn, "month": month}, ignore_index=True)

In [81]:
def convert_month2(month):
    if month == 1:
        return "Jan"
    elif month == 2:
        return "Feb"
    elif month == 3:
        return "Mar"
    elif month == 4:
        return "Apr"
    elif month == 5:
        return "May"
    elif month == 6:
        return "Jun"
    elif month == 7:
        return "Jul"
    elif month == 8:
        return "Aug"
    elif month == 9:
        return "Sep"
    elif month == 10 :
        return "Oct"
    elif month == 11:
        return "Nov"
    elif month == 12:
        return "Dec"
    else:
        return month

#df = pd.DataFrame({"month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]})
df["month"] = df["month"].apply(convert_month2)

print(df)

     GPN month
0   GPN1   Jan
1   GPN1   Feb
28  GPN1   Mar
29  GPN1   Apr
2   GPN1   May
3   GPN1   Jun
4   GPN1   Jul
5   GPN1   Aug
6   GPN1   Sep
7   GPN1   Oct
8   GPN2   Feb
30  GPN2   Mar
9   GPN2   Apr
31  GPN2   May
10  GPN2   Jun
11  GPN2   Jul
12  GPN2   Aug
13  GPN2   Sep
14  GPN2   Oct
15  GPN2   Nov
16  GPN3   Jan
17  GPN3   Feb
18  GPN3   Mar
19  GPN3   Apr
20  GPN3   May
21  GPN3   Jun
22  GPN3   Jul
23  GPN3   Aug
24  GPN3   Sep
25  GPN3   Oct
26  GPN3   Nov
27  GPN3   Dec